### ISSUE TITLE
Split off into lib

### ISSUE THREAD

**Issue by Christoph-AK** [Noratrieb/jsonformat#6]
Hey, thanks for this crate, really helpful and easy to use.

I'm only using your lib in another rust application, so I just call one line of `let pretty = jsonformat::format_json(&pretty, jsonformat::Indentation::Default);`. 

For this I clap gets included into the dependencies, which is not quite neccessary for my use case. 

It would be great if you could split of the lib and reupload it as another crate, on which the CLI tool can then depend.

**Comment by Noratrieb** [comment]
Thank you for the report! Ugh, that's pretty stupid that clap is included in the normal deps, I'm gonna fix that today or over the weekend

**Comment by Noratrieb** [comment]
Note that you can just disable the default features which will get rid of clap while I split this up nicely

**Comment by Noratrieb** [comment]
I released a new version splitting the binary into a new crate (`jsonformat-cli`) and also cleaned up the whole crate (making some breaking changes, but migration should be trivial).

https://crates.io/crates/jsonformat

**Comment by Christoph-AK** [comment]
Thanks so much for the quick rework ❤️ Amazing!
